project_id = "cbqkoverzdzmhceztldv"

[functions.migrate-app-users]
verify_jwt = false

[functions.auto-renda-extra]
verify_jwt = false

[functions.snapshot-daily]
verify_jwt = false

[functions.iam-control-receive-aluno]
verify_jwt = false

[functions.iam-control-pull-clientes]
verify_jwt = false

[functions.iam-control-contrato]
verify_jwt = false

